<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_consulta</name>
   <tag></tag>
   <elementGuidId>6de54b45-333b-4ef4-b08c-3a1513cf9465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/ul/li[5]/ul[2]/li/ul[2]/li/ul[1]/li/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
